/*
 * Camera Roll
 */

export const CAMERA_ROLL_GET_PHOTOS_INIT = 'CAMERA_ROLL_GET_PHOTOS_INIT';
export const CAMERA_ROLL_GET_PHOTOS_START = 'CAMERA_ROLL_GET_PHOTOS_START';
export const CAMERA_ROLL_GET_PHOTOS_SUCCESS = 'CAMERA_ROLL_GET_PHOTOS_SUCCESS';
export const CAMERA_ROLL_GET_PHOTOS_FAILURE = 'CAMERA_ROLL_GET_PHOTOS_FAILURE';

export const CAMERA_ROLL_GET_MORE_PHOTOS_START =
  'CAMERA_ROLL_GET_MORE_PHOTOS_START';
export const CAMERA_ROLL_GET_MORE_PHOTOS_SUCCESS =
  'CAMERA_ROLL_GET_MORE_PHOTOS_SUCCESS';
export const CAMERA_ROLL_GET_MORE_PHOTOS_FAILURE =
  'CAMERA_ROLL_GET_MORE_PHOTOS_FAILURE';
